server:
  port: 8082 #配置中心端口
spring:
  application:
    name: logistics-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息间隔时间 (默认为30秒)
  instance:
    lease-expiration-duration-in-seconds: 60  # 注册中心超过这个时间没收到心跳，会视为无效节点(默认为90秒)
    lease-renewal-interval-in-seconds: 30  # 发送心跳间隔时间（默认30秒）
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
