server:
    servlet:
        context-path: /trafficPlug
    # 服务端口号
    port: 8096
    tomcat:
        threads:
            min-spare: 100
            max: 400
        max-connections: 10000
        accept-count: 1000
spring:
    application:
        # 服务名称 - 服务之间使用名称进行通讯
        name: traffic-plug
    main:
        allow-bean-definition-overriding: true
eureka:
    client:
        service-url:
            # 填写注册中心服务器地址
            defaultZone: http://68.32.134.8:8080/eureka
#            defaultZone: http://127.0.0.1:8080/eureka
        # 是否需要将自己注册到注册中心
        register-with-eureka: true
        # 是否需要搜索服务信息
        fetch-registry: true
    instance:
        # 使用ip地址注册到注册中心
        prefer-ip-address: true
        # 注册中心列表中显示的状态参数
        instance-id: ${spring.cloud.client.ip-address}:${server.port}

swagger:
    enabled: true
    title: 插件数据接口
    base-package: com.xdh

logging:
    level:
        com.xdh: debug
